adding 1-run_inline file

diff --git a/0x00-python-hello_world/1-run_inline b/0x00-python-hello_world/1-run_inline
--- a/0x00-python-hello_world/1-run_inline
+++ b/0x00-python-hello_world/1-run_inline
@@ -1,3 +1,10 @@
-#!/usr/bin/python3
+#!/bin/bash
 
-print(f"Best School: {88+10}")
+# Check if the PYCODE environment variable is set
+if [ -z "$PYCODE" ]; then
+    echo "Error: PYCODE environment variable is not set."
+    exit 1
+fi
+
+# Run the Python code specified by PYCODE
+python3 -c "$PYCODE"
